Enhance frontend
cesium/cesium_cup pull request #35
Opened 2023-02-22 09:47 UTC by joaodiaslobo

This pull request includes enhancements to the UI elements across most pages. The modifications consist of an improved team page UI, better player team UI, a more engaging match page with icons to represent player events, a footer, and mobile responsiveness.

All updates have been made in accordance with the figma design file. _Relevant images that showcase the modifications are included below for reference:_

![image](https://user-images.githubusercontent.com/30907944/220576928-9fc3eb9c-c12b-418e-a252-9bf4d99f4063.png)
![image](https://user-images.githubusercontent.com/30907944/220577203-06990851-7230-433f-97a1-96b73b0cfb75.png)
![image](https://user-images.githubusercontent.com/30907944/220577932-ea9362d6-5c0e-4f38-b506-b0ad77b58729.png)
![image](https://user-images.githubusercontent.com/30907944/220578681-7879e92e-7afa-4112-86c9-2fdb2e4579a5.png)
![image](https://user-images.githubusercontent.com/30907944/220578196-f1ad6113-a09d-4c94-be6c-cd76a24bd0c4.png)

2023-02-22 11:10 UTC, MarioRodrigues10 requested changes
Please rebase this PR in order to get main recent changes.

2023-02-22 11:21 UTC, MarioRodrigues10 requested changes

2023-02-22 11:21 UTC, MarioRodrigues10 commented on lib/cesium_cup_web/live/player_live/show.html.heex
> +                      <span><%= live_patch("Edit", to: Routes.match_index_path(@socket, :edit, match), class: "text-gray-900") %></span>
```suggestion
                      <span><%= live_redirect("Edit", to: Routes.match_index_path(@socket, :edit, match), class: "text-gray-900") %></span>
```

2023-02-22 11:21 UTC, MarioRodrigues10 commented on lib/cesium_cup_web/live/team_live/show.html.heex
> +      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_patch("Edit team", to: Routes.team_show_path(@socket, :edit,
```suggestion
      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_redirect("Edit team", to: Routes.team_show_path(@socket, :edit, @team), class: "button") %></span>
```

2023-02-22 11:21 UTC, MarioRodrigues10 commented on lib/cesium_cup_web/live/match_live/show.html.heex
> +      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_patch("Edit match", to: Routes.match_show_path(@socket, :edi
```suggestion
      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_redirect("Edit match", to: Routes.match_show_path(@socket, :edit, @match), class: "button") %></span>
```

2023-02-22 11:21 UTC, MarioRodrigues10 commented on lib/cesium_cup_web/live/group_live/show.html.heex
> +      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_patch("Edit group", to: Routes.group_show_path(@socket, :edi
```suggestion
      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_redirect("Edit group", to: Routes.group_show_path(@socket, :edit, @group), class: "button") %></span>
```

2023-02-22 11:21 UTC, MarioRodrigues10 commented on lib/cesium_cup_web/live/player_live/show.html.heex
> +      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_patch("Edit player", to: Routes.player_show_path(@socket, :e
```suggestion
      <span class="border-transparent ml-auto mr-4 text-indigo-300 hover:text-indigo-400 whitespace-nowrap border-b-4 font-small"><%= live_redirect("Edit player", to: Routes.player_show_path(@socket, :edit, @player), class: "button") %></span>
```

2023-02-22 14:16 UTC, MarioRodrigues10 requested changes
Please run ```mix format``` in order to pass CI

2023-02-22 17:37 UTC, MarioRodrigues10 submitted a review, later dismissed
There's a few changes you'll have to do:
1st - make sure every page design is responsive
2nd - ```/players``` could you enhance this page
3rd - please enhance ```edit``` pages

2023-02-25 23:07 UTC, joaodiaslobo commented
Changed player page to match Figma design.

![image](https://user-images.githubusercontent.com/30907944/221383652-d75b2cbf-32a4-4d84-a2d1-b887f2fa38a0.png)

2023-08-23 16:31 UTC, RuiL1904 commented on lib/cesium_cup_web/live/player_live/show.ex
> +  end
This function should be inside an helpers module 💡

2023-08-23 16:32 UTC, RuiL1904 commented on lib/cesium_cup_web/live/player_live/show.ex
> +  end
From what I can see, `ViewUtils` already exist. Put it there 👌🏼

2023-08-25 03:11 UTC, feliciofilipe approved these changes
🙏🙏

2023-08-25 14:30 UTC, merged